channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::ipython==8.3.0
  - conda-forge::ipykernel==6.13.0
  - conda-forge::pandas==1.4.2
  - conda-forge::python-igraph==0.9.10
  - conda-forge::leidenalg==0.8.10
  - conda-forge::umap-learn==0.5.3
  - conda-forge::seaborn==0.11.2
  - conda-forge::statsmodels==0.13.2
  - conda-forge::gawk==5.1.0
  - conda-forge::coreutils==8.31
  - conda-forge::sed==4.8
  - conda-forge::bash==5.0.018
  - conda-forge::gzip==1.10
  - conda-forge::datamash==1.7
